### ISSUE TITLE
No signature of method: nebula.plugin.metrics.collector.GradleCollector.buildFinishedClosure() 

### ISSUE THREAD

**Issue by dbahlbeck** [nebula-plugins/gradle-metrics-plugin#13]
Hi,

I get this error at the end of any Gradle task execution in my project:

No signature of method: nebula.plugin.metrics.collector.GradleCollector.buildFinishedClosure() is applicable for argument types: () values: []

I am using 4.1.5 and have customized the build with:
metrics {
  hostname = '<server>'    // default is 'localhost'
  httpPort = 9200            // default is 9200
  indexName = 'build-metrics'   // default is 'build-metrics-default'
  dispatcherType = 'ES_HTTP'
}

Any ideas what the problem could be?

Thanks,
David

**Comment by nadavc** [comment]
That's interesting. What version of Gradle are you using?

**Comment by dbahlbeck** [comment]
I'm using Gradle 2.10

**Comment by nadavc** [comment]
Would it be possible to provide a small reproducible example?

**Comment by dbahlbeck** [comment]
I've created a small project here: https://github.com/wursley/gradle-metrics-test.git

Here we have a slightly different setup with the external repositories because we are behind a proxy, so I have updated that to just point to jcenter.

Just running 'gradlew test' is enough to get the error.

**Comment by nadavc** [comment]
Thanks. I was able to reproduce the bug as described. Until we pinpoint the source of this, you could include and apply the [nebula.info](https://github.com/nebula-plugins/gradle-info-plugin) plugin as a quick workaround.
