### ISSUE TITLE
Make error message suppression configurable

### ISSUE THREAD

**Issue by nadavc** [nebula-plugins/gradle-metrics-plugin#15]
Error messages are currently logged using `logger.debug()` in order to reduce noise in build output. It would be nice to make this configurable by toggling a flag in the `metrics` extension to output to `info` or `error` instead.

**Comment by DanielThomas** [comment]
I'm closing all open issues because we've adopted Gradle Enterprise and we'll be no longer maintaining this plugin. It was already difficult maintaining compatibility due to internal API use, but Gradle 7 and configuration caching will make keeping this working impossible without a rewrite.
