### ISSUE TITLE
Usage - REST call build metrics is empty

### ISSUE THREAD

**Issue by vivsrivastav** [nebula-plugins/gradle-metrics-plugin#24]
I integrated the plugin with my spring-boot project. I am collecting the metrics data on my localhost POST end point. However the endpoint is getting empty result except for the dates. 
Sample  below:-
{"eventName":"build_metrics","payload":{"build":"{\"events\":[],\"tasks\":[],\"tests\":[],\"result\":{\"status\":\"unknown\"},\"startTime\":\"2017-06-24T05:57:13.647Z\",\"elapsedTime\":0,\"testCount\":0,\"taskCount\":0,\"eventsCount\":0,\"eventsElapsedTime\":0,\"tasksElapsedTime\":0,\"testElapsedTime\":0,\"finishedTime\":\"2017-06-24T05:57:13.647Z\"}","buildId":"2593ebc5-c56a-4a60-a087-42239810d20b"}}

I noticed in the debugger that the command ./gradlew build or ./gradlew test invokes the POST call even before the compilation starts.

How can i control the plugin to invoke Post with build data with the failing tests? It would be helpful if you could add a sample project that uses this plugin to post build metrics using REST. 

Here is the code snippet from my build.gradle
apply plugin: "nebula.metrics"
metrics {
    dispatcherType = 'REST'
    restUri = 'http://localhost:8000/metrics'
}

**Comment by tylrd** [comment]
The MetricDispatcher makes an HTTP request on start and finish of the build. That response looks like it's the initial request when the build starts. Did you let the build finish and see if a second request was made with populated data?

**Comment by vivsrivastav** [comment]
Yes i found that later. My debugger was on so kept debugging the 1st request and lost 2nd request in the process. Thanks
Closing this
