### ISSUE TITLE
Deprecated HTTP headers in the docs

### ISSUE THREAD

**Issue by fml2** [nebula-plugins/gradle-metrics-plugin#63]
The example on https://swingletree-oss.github.io/swingletree/docs/plugins/nebula/ recommends to use `X-...` headers. The usage of X-Headers was deprecated in June 2012. Our experiments also show that the data transfer also works with the headers without "X-" quite fine, e.g. `swingletree-org` instead of `X-swingletree-org`.

Hence I think the docs could be adjusted to use the headers withot "X-".

**Comment by rpalcolea** [comment]
Hi! 

We don’t own swingletree. You might want to bring this up in https://github.com/swingletree-oss/swingletree/blob/master/docs/_docs/plugins/nebula.md

Since this is something we can’t fix, I’ll close this issue

**Comment by fml2** [comment]
Oh yes, sorry for the hassle, my fault.

**Comment by rpalcolea** [comment]
no problem! thanks for bring it up :)
