### ISSUE TITLE
Nebula plugin version compatibility issues with Gradle 6.1+ versions

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [nebula-plugins/gradle-metrics-plugin#65]
I am using below nebula dependency versions with Gradle 6.1 version, Still I am getting the same issue.
```
compile "com.netflix.nebula:gradle-info-plugin:8.0.0"
compile "com.netflix.nebula:nebula-release-plugin:14.0.5"
compile "com.netflix.nebula:gradle-metrics-plugin:10.0.1"
compile "com.netflix.nebula:gradle-lint-plugin:16.9.0"
compile "com.netflix.nebula:nebula-publishing-plugin:17.0.0"
```
Error:
Caused by: java.lang.NoSuchMethodError: org.gradle.api.provider.Provider.forUseAtConfigurationTime()Lorg/gradle/api/provider/Provider;

**Comment by chali** [comment]
Hi @ramakrishnakaushik97 you are using `gradle-info-plugin:8.0.0` which requires Gradle `6.5+` https://github.com/nebula-plugins/gradle-info-plugin/releases/tag/v8.0.0

You mentioned that you are using only 6.1+.
